# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Make Release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: zip
        path: build/distributions/scrimbot-api-${{ github.event.inputs.version_number }}.zip
        if-no-files-found: error  
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: zip
          path: .
      - name: Show Artifacts
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version_number }}
          name: Version ${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          artifacts: "*.zip"
          body: |
            ${{ github.event.inputs.info }}
            
            ---
            ### Setup
            Setup instructions can be found in the [README section](https://github.com/Martig3/scrimbot-api#setup)
            
            # Download: [scrimbot-api-${{ github.event.inputs.version_number }}.jar](https://github.com/Martig3/scrimbot-api/releases/download/${{ github.event.inputs.version_number }}/scrimbot-api-${{ github.event.inputs.version_number }}.jar)
